### PR TITLE
Added Jwt.Net to adopters.csv

### PR DESCRIPTION
**Pull request by abatishchev**

### CODE REVIEW

**Review by CoralineAda — COMMENTED** [review]
I see an MIT license in that repo?

**Comment by abatishchev** [comment]
Dual licensed, if you don't mind. You'd prefer fully switched?

**Comment by CoralineAda** [comment]
No, dual license is fine. I just couldn’t find it anywhere? Did I miss it in the license file?

**Comment by abatishchev** [comment]
Let me take it back and reconsider how to better organize my repo and express the licensing model.

**Pull request closed without merging**
