### PR TITLE
Add a little specificity to the harm clause

### PR DESCRIPTION
**Pull request by Cantido**
There is the potential to maliciously misinterpret the harm clause in order to protect groups in power.
As it stands, it could be interpreted as a clause against "punching," not against specifically "punching down," which I believe its intent.

This change makes it a little more difficult to maliciously interpret the harm clause to protect groups in power.

### CODE REVIEW

**Comment by CoralineAda** [comment]
What do you think of "underprivileged"?

**Comment by Cantido** [comment]
I think "underprivileged" works well, too. What makes it a better choice, do you think?

**Comment by CoralineAda** [comment]
Makes it about power differentials, which is culturally agnostic.

**Comment by Cantido** [comment]
Gotcha! I totally agree with you; it's a better choice.

**Comment by CoralineAda** [comment]
Make that small change and I'll merge. Thanks!

**Review by CoralineAda — APPROVED** [review]

**Comment by CoralineAda** [comment]
🖤

**Comment by aitor** [comment]
Sorry for commenting in a closed PR but I was wondering if the same term should be used in this paragraph (for the same reasons commented here):

> All of these technologies are inherently political. There is no neutral political position in technology. You can't build systems that can be weaponized against **marginalized** people and take no responsibility for them.

cf. https://github.com/ContributorCovenant/hippocratic-license/blob/release/content/_index.md

PS: Thank you very much for creating this @CoralineAda

**Pull request merged**
